config/routes.rb
TusurDiplomer::Application.routes.draw do
  devise_for :users

  match 'diplomas/:id/pdf' => 'diplomas#pdf', :defaults => {:format => :pdf}, :as => 'pdf_diploma'
  match 'academic_records/:id/pdf' => 'academic_records#pdf', :defaults => {:format => :pdf}, :as => 'pdf_academic_record'

  match 'academic_records/:id/debug' => 'academic_records#debug'

  resources :diplomas do
    resources :student
    resources :courses
    resources :papers
    resources :practices
    resources  :final_state_examinations

    resource  :final_qualification_project

    resources :programm_items, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :academic_records do
    resources :courses

    resources :courses, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :chairs
  resources :disciplines,  :except => :show
  resources :faculties,    :except => :show

  resources :specialities do
    resources :courses
    resources :papers
    resources :practices
    resources  :final_state_examinations
    resources :programm_items, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :suggestions,  :only => :index
  resources :users

  resources :people do
    resources :roles, :except => [:index,:show]
  end

  root :to => "application#index"
end

app/models/diploma.rb
# encoding: utf-8

class Diploma < ActiveRecord::Base
  has_programm_items

  belongs_to :chair
  belongs_to :faculty
  belongs_to :speciality

  has_one :final_qualification_project, :dependent => :destroy, :as => :context
  has_one :student,                     :dependent => :destroy, :as => :studentable

  validates_presence_of :speciality, :admission_date, :graduation_date,
                        :study_form, :total_hours, :chair,
                        :access_requirements

  accepts_nested_attributes_for :student, :update_only => true

  after_create :create_final_qualification_project
  after_create :create_program_items

  before_save :generate_number

  has_autosuggest_for :speciality

  default_scope :order => 'number DESC'

  has_enum :study_form, %w[fulltime parttime postal]
  has_enum :access_requirements, %w[bachelor_diploma specialist_diploma certificate_of_complete_secondary_education
                                    certificate_of_professional_education certificate_of_vocational_education]

  delegate :full_info, :to => :student, :prefix => true

  default_value_for :access_requirements, 'certificate_of_complete_secondary_education'

  def is_translated?
    student.is_translated? && final_state_examination.is_translated? && final_qualification_project.is_translated?
  end

  def duration
    result = graduation_date.year - admission_date.year
  end

  def eng_duration
    "#{::I18n.t('duration.eng_year', :count => duration)}"
  end

  def rus_duration
    "#{::I18n.t('duration.year', :count => duration)}"
  end

  def average_grade
    total = 0.0
    count = 0.0
    total += 3 * programm_items.grade_satisfactorily.count
    count += programm_items.grade_satisfactorily.count
    total += 4 * programm_items.grade_good.count
    count += programm_items.grade_good.count
    total += 5 * programm_items.grade_excellent.count
    count += programm_items.grade_excellent.count
    count > 0 ? (total / count).round(1) : 0
  end

  def to_s
    "Диплом №#{number}"
  end
  alias_method :title, :to_s

  def real_faculty
    faculty || chair.faculty
  end

  searchable do
    text :search_string do
      "#{student_surname} #{chair_abbr} #{chair_title} #{I18n.l graduation_date, :format => '%Y'}"
    end
  end

  delegate :surname, :to => :student, :prefix => true
  delegate :abbr, :title, :to => :chair, :prefix => true

  def access_requirements_eng
    I18n.t("activerecord.attributes.#{self.class.name.underscore}.access_requirements_eng.#{access_requirements}")
  end

  private

  def generate_number
    diplomas = self.class.where(:graduation_date => (self.graduation_date.at_beginning_of_year..self.graduation_date.at_end_of_year),
                                :chair_id => self.chair.id)

    if last_diploma = diplomas.first
      number = last_diploma.serial_number + 1
    else
      number = 1
    end
    formatted_number = sprintf("%05i",number)

    self.eng_number = "#{chair.eng_abbr.upcase}#{I18n.l graduation_date, :format => '%y'}-#{formatted_number}"
    self.number = "#{chair.abbr.upcase}#{I18n.l graduation_date, :format => '%y'}-#{formatted_number}"
    self.serial_number = number
  end

  def create_program_items
    %w[courses papers practices final_state_examinations].each do |association|
      self.speciality.send(association).each do |item|
        i = item.clone
        i.context = self
        i.save(:validate => false)
      end
    end
  end
end

# == Schema Information
#
# Table name: diplomas
#
#  id                  :integer          not null, primary key
#  speciality_id       :integer
#  number              :string(255)
#  admission_date      :date
#  graduation_date     :date
#  study_form          :string(255)
#  study_duration      :string(255)
#  total_hours         :integer
#  created_at          :datetime
#  updated_at          :datetime
#  chair_id            :integer
#  eng_number          :string(255)
#  serial_number       :integer
#  faculty_id          :integer
#  access_requirements :string(255)
#

app/controllers/diplomas_controller.rb
# encoding: utf-8

class DiplomasController < CrudController
  def show
    show!{
      @course = @diploma.courses.new
      @paper = @diploma.papers.new
      @practice = @diploma.practices.new
      @final_state_examination = @diploma.final_state_examinations.new
    }
  end

  def pdf
    @diploma = Diploma.find(params[:id])
    @student = Student.find(@diploma.student)
    @speciality = Speciality.find(@diploma.speciality)
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "#{@diploma}-#{@diploma.student}",
          :stylesheets => ["print"],
          :disposition => 'inline'
      end
    end
  end
end

app/views/diplomas/_form.html.erb
<%= form.fields_for :student do |student| %>
  <%= student.inputs do %>
    <%= student.input :surname, :input_html => {:tabindex => '1'} %>
    <%= student.input :eng_surname, :wrapper_html => {:class => 'right'}, :input_html => {:tabindex => '4'} %>
    <%= student.input :firstname, :input_html => {:tabindex => '2'} %>
    <%= student.input :eng_firstname, :wrapper_html => {:class => 'right'}, :input_html => {:tabindex => '5'} %>
    <%= student.input :patrynomic, :input_html => {:tabindex => '3'} %>
    <%= student.input :eng_patrynomic, :wrapper_html => {:class => 'right'}, :input_html => {:tabindex => '6'} %>
    <%= student.input :code, :input_html => {:tabindex => '7'} %>
    <%= student.input :birthday, :input_html => {:tabindex => '8'} %>
  <% end %>
<% end %>

<%= form.inputs do %>
  <%= form.input :faculty, :wrapper_html => {:class => 'right wide'}, :input_html => {:tabindex => '9'} %>
  <%= form.input :chair, :wrapper_html => {:class => 'right wide'}, :input_html => {:tabindex => '9'} %>
  <%= form.input :speciality_id, :as => :hidden, :input_html => {:tabindex => '10'} %>
  <%= form.input :speciality_term, :required => true, :wrapper_html => {:class => 'right wide'}, :input_html => {:tabindex => '11'} %>
  <%= form.input :access_requirements, :wrapper_html => {:class => 'right wide'}, :input_html => {:tabindex => '11'} %>
  <%= form.input :admission_date, :input_html => {:tabindex => '12'} %>
  <%= form.input :graduation_date, :input_html => {:tabindex => '13'} %>
  <%= form.input :study_form, :input_html => {:tabindex => '14'} %>
  <%= form.input :total_hours, :input_html => {:tabindex => '15'} %>
<% end %>

app/views/diplomas/_item.html.erb
<li class="<%= item.class.name.downcase %> item">
  <h4>
    <%= link_to t(:edit), edit_resource_url(item), :class => "edit" %>

    <% if controller.respond_to?(:show) %>
      <%= link_to "#{item} - #{item.student_full_info}", resource_path(item) %>
    <% else %>
      <%= item.title %>
    <% end %>
  </h4>

  <% if item.respond_to? :translated? %>
    <% unless item.translated? %>
      <p><%= t('translate_missing') %></p>
    <% end %>
  <% end %>
</li>

app/views/diplomas/_search_form.html.erb
<%= semantic_search_form_for :diploma, :url => diplomas_path, :html => {:method => :get, :class => 'search_form'} do |form| %>
  <%= form.inputs do %>
    <%= form.input :search_string %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button 'Найти', :button_html => {:class => 'button'} %>
  <% end %>
<% end %>

app/views/diplomas/pdf.pdf.erb
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.1//EN' 'http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
  <head>
    <meta http-equiv='Content-Type' content='text/html;charset=UTF-8' />
    <title><%= @diploma %></title>
    <%= stylesheet_link_tag 'print' %>
  </head>
  <body>
    <div class='first_side'>
      <div class='left_side'>
        <div class='faculty_name'>
          <p class='eng'><%= @diploma.real_faculty.eng_title %></p>
          <p class='rus'><%= @diploma.real_faculty.title %></p>
        </div>
        <div class='diploma_number'>
          <%= @diploma.eng_number %>
        </div>
      </div>

      <div class='right_side'>
        <div class='holder_info'>
          <div class='surname'>
            <p class='eng'><%= @student.eng_surname %></p>
            <p class='rus'><%= @student.surname %></p>
          </div>
          <div class='given_name'>
            <p class='eng'><%= "#{@student.eng_firstname} #{@student.eng_patrynomic}" %></p>
            <p class='rus'><%= "#{@student.firstname} #{@student.patrynomic}" %></p>
          </div>
          <div class='birthdate'>
            <p><%= "#{@student.birthday.strftime('%B %d, %Y')} / #{l(@student.birthday, :format => '%d %B, %Y')}" %></p>
          </div>
          <div class='student_code'>
            <p><%= @student.code %></p>
          </div>
        </div>

        <div class='qualification_info'>
          <div class='qualification'>
            <p class='eng'><%= @speciality.eng_qualification %></p>
            <p class='rus'><%= @speciality.qualification %></p>
          </div>
          <div class='speciality'>
            <p class='eng'><%= @speciality.eng_title %></p>
            <p class='rus'><%= @speciality.title %></p>
          </div>
          <div class='award_institute'>
            <p class='eng'>Tomsk State University of Control Systems and Radioelectronics, State University</p>
            <p class='rus'>Томский государственный университет систем управления и радиоэлектроники</p>
          </div>
          <div class='admin_institute'>
            <p class='eng'>Tomsk State University of Control Systems and Radioelectronics</p>
            <p class='rus'>Томский государственный университет систем управления и радиоэлектроники</p>
          </div>
          <div class='language'>
            <p class='eng'>Russian</p>
            <p class='rus'>Русский</p>
          </div>
        </div>

        <div class='qualification_details'>
          <div class='level'>
            <p class='eng'>First stage of higher education</p>
            <p class='rus'>Высшее образование первой ступени</p>
          </div>
          <div class='durations'>
            <p class='eng'>
              <%= @diploma.eng_duration %>&#59; total: <%= t('duration.eng_hour', :count => @diploma.total_hours) %>
            </p>
            <p class='rus'>
              <%= @diploma.rus_duration %>&#59; всего: <%= t('duration.hour', :count => @diploma.total_hours) %>
            </p>
          </div>
          <div class='access_requirements'>
            <p class='eng'><%= @diploma.access_requirements_eng %><br/>Entrance examinations</p>
            <p class='rus'><%= @diploma.human_access_requirements %><br/>Вступительные экзамены</p>
          </div>
        </div>
      </div>

    </div>

    <div class='second_side'>
      <div class='contents_info'>
        <div class='study_mode'>
          <p class='eng'>Admission &ndash; <%= @diploma.admission_date.strftime('%B %d, %Y') %>&#59; graduation &ndash; <%= @diploma.graduation_date.strftime('%B %d, %Y') %> (<%= Diploma.human_attribute_name("eng_study_form_enum.#{@diploma.study_form}") %>)</p>
          <p class='rus'>Дата зачисления &ndash; <%= l(@diploma.admission_date, :format => '%d %B %Y') %>&#59; дата окончания обучения &ndash; <%= l(@diploma.graduation_date, :format => '%d %B %Y') %><%= " (#{@diploma.human_study_form})" %></p>
        </div>
        <div class='programm_requirments'>
          <p>Compulsory subjects / Обязательные дисциплины &ndash; <%= @diploma.courses.count %></p>
          <p>Course Papers / Курсовые работы &ndash; <%= @diploma.papers.count %></p>
          <p>Practice / Практика &ndash; <%= @diploma.practices.count %> </p>
        </div>
      </div>
      <div class='programm_details'>
        <table>
          <thead>
            <tr>
              <th>Course</th>
              <th class='credits'>ECTS / Credits</th>
              <th class='hours'>Hours</th>
              <th class='grades'>Grades</th>
            </tr>
          </thead>
          <tbody>
            <% @diploma.courses.each_with_index do |course, index| %>
              <tr>
                <td><%= "#{index + 1}. " %><%= "#{course.eng_title} / #{course.title}" %></td>
                <td class='credits'><%= course.credits %></td>
                <td class='hours'><%= course.hours %></td>
                <td class='grades'><%= course.human_grade %></td>
              </tr>
            <% end %>

            <%# NOTE: так сделато чтобы дисциплины были на нужной странице %>
            <% if false && @diploma.courses.count < 47 %>
              <% (@diploma.courses.count + 1..47).each do %>
                <tr>
                  <td style="border: none"></td>
                  <td class="credits" style="border: none"></td>
                  <td class="hours" style="border: none"></td>
                  <td class="grades" style="border: none"></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <table class='paper_table'>
          <tbody>
            <tr class='title course_paper'>
              <td colspan='4'>Course Papers In</td>
            </tr>
            <% @diploma.papers.each_with_index do |paper, index| %>
              <tr>
                <td colspan='3'><%= "#{index + 1}. " %><%= "#{paper.eng_title} / #{paper.title}" %></td>
                <td class='grades'><%= paper.human_grade %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <table class='practice_table'>
          <tbody>
            <tr class='title'>
              <td colspan='4'>Practice</td>
            </tr>
            <% @diploma.practices.each_with_index do |practice, index| %>
              <tr>
                <td><%= "#{index + 1}. " %><%= "#{practice.eng_title} / #{practice.title}" %></td>
                <td class='credits'><%= practice.credits %></td>
                <td class='hours'><%= practice.weeks %></td>
                <td class='grades'><%= practice.human_grade %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <table class='state_examination_table'>
          <tbody>
            <tr class='title'>
              <td colspan='4'>Final State Examinations</td>
            </tr>
            <% @diploma.final_state_examinations.each_with_index do |final_state_examination, index| %>
              <tr class='state_examination'>
                <td colspan='3'><%= "#{index + 1}. "%><%= final_state_examination.eng_title %> / <%= final_state_examination.title %></td>
                <td class='grades'><%= final_state_examination.human_grade %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <table class='qualification_table'>
          <tbody>
            <tr class='title'>
              <td colspan='4'>Final Qualification Project</td>
            </tr>
            <tr class='qualification_project'>
              <td><%= @diploma.final_qualification_project.eng_title %> / <%= @diploma.final_qualification_project.title %></td>
              <td class='credits'><%= @diploma.final_qualification_project.credits %></td>
              <td class='hours'><%= @diploma.final_qualification_project.weeks %></td>
              <td class='grades'><%= @diploma.final_qualification_project.human_grade %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class='average'>
        <p><span class='left' >Average Grade</span> <span class='right'><%= @diploma.average_grade %></span> </p>
      </div>
      <div class='certification'>
        <h2>Certification of the supplement</h2>
        <p><span class='left'>Rector of Tomsk State University of Control Systems and Radioelectronics</span><span class='right'><%= t 'rector_name' %></span></p>
        <p><span class='left'><%= @diploma.real_faculty.chief_post %> <%= @diploma.real_faculty.eng_title %></span><span class='right'><%= @diploma.real_faculty.chief_name %></span>
      </p>
      </div>
    </div>
  </body>
  </html>

app/views/diplomas/show.html.erb
<% title resource %>

<%= link_to t(:edit), edit_diploma_path, :class => 'button floatr' %>
<%= link_to 'Печать шаблона', pdf_diploma_path(resource), :class => 'button floatr print', target: '_blank' %>

<%= show_for resource do |item| %>
  <%= item.association :student, :using => :full_info %>
  <%= item.attributes :number, :eng_number, :chair, :speciality, :access_requirements, :admission_date, :graduation_date, :study_form, :total_hours %>
<% end %>

<ul class='tabs_menu'>
  <li class='first'><%= link_to "Дисциплины", '#', :class => 'courses' %></li>
  <li><%= link_to "Курс. работы", '#', :class => 'papers' %></li>
  <li><%= link_to "Практики", '#', :class => 'practices' %></li>
  <li><%= link_to "Гос. экзамен", '#', :class => 'state_examination' %></li>
  <li class='last'><%= link_to "Квал. работа", '#', :class => 'qualification_project' %></li>
</ul>

<div class='details_wrapper'>
  <ul class='details'>
    <li id='courses'>
      <div class="headline">
        <span class='title'>Название</span>
        <span class='eng_title'>Название на англ. языке</span>
        <span class='credits'>Баллы</span>
        <span class='hours'>Часы</span>
        <span class='human_grade'>Оценка</span>
      </div>
      <ol class='courses_list list' id='courses_list' data-sort-url="<%= sort_diploma_programm_items_path(resource) %>">
        <% if @diploma.courses.any? %>
          <% @diploma.courses.order('position DESC').each do |course| %>
            <li class="item" id="programm_item_<%= course.id %>">
              <%= render :partial => "courses/course", :locals => {:course => course} %>
            </li>
          <% end %>
        <% else %>
          <li class='empty'>нет дисциплин</li>
        <% end %>
      </ol>
      <div class='form_new'>
        <%= render :file => "courses/new.html.erb" %>
      </div>
    </li>

    <li id='papers'>
      <div class="headline">
        <span class='title'>Название</span>
        <span class='eng_title'>Название на англ. языке</span>
        <span class='human_grade'>Оценка</span>
      </div>
      <ol class='papers_list list' id='papers_list' data-sort-url="<%= sort_diploma_programm_items_path(resource) %>">
        <% if @diploma.papers.any? %>
          <% @diploma.papers.order('position DESC').each do |paper| %>
            <li class="item" id="programm_item_<%= paper.id %>">
              <%= render :partial => "papers/paper", :locals => {:paper => paper} %>
            </li>
          <% end %>
        <% else %>
          <li class='empty'>нет курсовых работ</li>
        <% end %>
      </ol>
      <div class='form_new'>
        <%= render :file => "papers/new.html.erb" %>
      </div>
    </li>

    <li id='practices'>
      <div class="headline">
        <span class='title'>Название</span>
        <span class='eng_title'>Название на англ. языке</span>
        <span class='credits'>Баллы</span>
        <span class='hours'>Недели</span>
        <span class='human_grade'>Оценка</span>
      </div>
      <ol class='practices_list list' id='practices_list' data-sort-url="<%= sort_diploma_programm_items_path(resource) %>">
        <% if @diploma.practices.any? %>
          <% @diploma.practices.order('position DESC').each do |practice| %>
            <li class="item" id="programm_item_<%= practice.id %>">
              <%= render :partial => "practices/practice", :locals => {:practice => practice} %>
            </li>
          <% end %>
        <% else %>
          <li class='empty'>нет практик</li>
        <% end %>
      </ol>
      <div class='form_new'>
        <%= render :file => "practices/new.html.erb" %>
      </div>
    </li>

    <li id='state_examination'>
      <div class="headline">
        <span class='title'>Название</span>
        <span class='eng_title'>Название на англ. языке</span>
        <span class='human_grade'>Оценка</span>
      </div>

      <ol class='final_state_examinations_list list' id='final_state_examinations_list'>
        <% if @diploma.final_state_examinations.any? %>
          <% @diploma.final_state_examinations.order('position ASC').each do |final_state_examination| %>
            <li class="item" id="programm_item_<%= final_state_examination.id %>">
              <%= render :partial => 'final_state_examinations/final_state_examination', :locals => { :final_state_examination => final_state_examination } %>
            </li>
          <% end %>
        <% else %>
          <li class='empty'>нет гос. экзаменов</li>
        <% end %>
      </ol>
      <div class='form_new'>
        <%= render :file => "final_state_examinations/new.html.erb" %>
      </div>
    </li>

    <li id='qualification_project'>
      <div class="headline">
        <span class='title'>Название</span>
        <span class='eng_title'>Название на англ. языке</span>
        <span class='credits'>Баллы</span>
        <span class='hours'>Недели</span>
        <span class='human_grade'>Оценка</span>
      </div>
      <ul class='qualification_project_list list'>
        <% if @diploma.final_qualification_project %>
          <li class="item">
            <%= render @diploma.final_qualification_project %>
          </li>
        <% else %>
          <li class='empty'>Нет квалификационной работы</li>
        <% end %>
      </ul>
    </li>
  </ul>
</div>