config/routes.rb
TusurDiplomer::Application.routes.draw do
  devise_for :users

  match 'diplomas/:id/pdf' => 'diplomas#pdf', :defaults => {:format => :pdf}, :as => 'pdf_diploma'
  match 'academic_records/:id/pdf' => 'academic_records#pdf', :defaults => {:format => :pdf}, :as => 'pdf_academic_record'

  match 'academic_records/:id/debug' => 'academic_records#debug'

  resources :diplomas do
    resources :student
    resources :courses
    resources :papers
    resources :practices
    resources  :final_state_examinations

    resource  :final_qualification_project

    resources :programm_items, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :academic_records do
    resources :courses

    resources :courses, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :chairs
  resources :disciplines,  :except => :show
  resources :faculties,    :except => :show

  resources :specialities do
    resources :courses
    resources :papers
    resources :practices
    resources  :final_state_examinations
    resources :programm_items, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :suggestions,  :only => :index
  resources :users

  resources :people do
    resources :roles, :except => [:index,:show]
  end

  root :to => "application#index"
end

app/models/person.rb
# encoding: utf-8

class Person < ActiveRecord::Base
  has_many :roles

  has_one :user, :dependent => :destroy

  validates_presence_of :firstname, :surname, :patrynomic

  accepts_nested_attributes_for :user

  delegate :email, :to => :user, :allow_nil => true

  default_scope :order => 'surname ASC'

  def name
    "#{surname} #{firstname} #{patrynomic}"
  end

  alias :to_s :name
end

# == Schema Information
#
# Table name: people
#
#  id         :integer          not null, primary key
#  surname    :string(255)
#  firstname  :string(255)
#  patrynomic :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/people_controller.rb
# encoding: utf-8

class PeopleController < CrudController
end

app/views/people/_view.html.erb
<%= show_for @person do |p| %>
  <%= p.attribute :surname %>
  <%= p.attribute :name %>
  <%= p.attribute :patrynomic %>
  <%= p.association :user, :label => 'Email' , :using => :email %>
  <%= p.association :roles, :label => 'Роль' %>

<% end %>

app/views/people/show.html.erb
<% title @person.name %>
<div class="formtastic">
  <fieldset>
    <%= render :partial => "view" %>
  </fieldset>
  <fieldset class="buttons">
    <ol>
      <li><%= link_to t(:edit), edit_resource_url, :class => "button" %></li>
    </ol>
    <ol>
      <li><%= link_to "Декан", new_person_role_path(@person, :type => :dean), :class => "button" %></li>
    </ol>
    <ol>
      <li><%= link_to "Заведующий кафедры", new_person_role_path(@person, :type => :chair_chief), :class => "button" %></li>
    </ol>
  </fieldset>
</div>