config/routes.rb
TusurDiplomer::Application.routes.draw do
  devise_for :users

  match 'diplomas/:id/pdf' => 'diplomas#pdf', :defaults => {:format => :pdf}, :as => 'pdf_diploma'
  match 'academic_records/:id/pdf' => 'academic_records#pdf', :defaults => {:format => :pdf}, :as => 'pdf_academic_record'

  match 'academic_records/:id/debug' => 'academic_records#debug'

  resources :diplomas do
    resources :student
    resources :courses
    resources :papers
    resources :practices
    resources  :final_state_examinations

    resource  :final_qualification_project

    resources :programm_items, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :academic_records do
    resources :courses

    resources :courses, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :chairs
  resources :disciplines,  :except => :show
  resources :faculties,    :except => :show

  resources :specialities do
    resources :courses
    resources :papers
    resources :practices
    resources  :final_state_examinations
    resources :programm_items, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :suggestions,  :only => :index
  resources :users

  resources :people do
    resources :roles, :except => [:index,:show]
  end

  root :to => "application#index"
end

app/models/academic_record.rb
# encoding: utf-8

class AcademicRecord < ActiveRecord::Base
  belongs_to :faculty

  has_many :semesters, :dependent => :destroy
  has_many :courses, :through => :semesters, :before_add => :set_context_type

  has_one :student, :dependent => :destroy, :as => :studentable

  accepts_nested_attributes_for :student, :update_only => true
  accepts_nested_attributes_for :semesters, :allow_destroy => true

  before_create :generate_number
  after_create  :create_semester, :if => Proc.new { |ar| ar.semesters.empty? }

  delegate :surname, :full_info,  :to => :student, :prefix => true
  delegate :abbr, :title,         :to => :faculty, :prefix => true

  searchable do
    text :search_string do
      "#{student_surname} #{faculty_abbr} #{faculty_title} #{I18n.l issue_date, :format => '%Y'}"
    end
  end

  def sort_courses(course_ids)
    course_ids.each_with_index do |course_id, index|
      # NOTE: avoid ActiveRecord::ReadOnlyRecord
      Course.where(:id => courses.map(&:id)).find(course_id).update_attribute(:position, index+1)
    end
  end

  def to_s
    "Академическая справка №#{number}"
  end

  def courses_grouped_by_semester
    semester_ids = courses.map(&:context_id).uniq
    ordered_semesters = Semester.where(:id => semester_ids)

    ordered_semesters.inject({}) do |hash, semester|
      hash[semester] = semester.courses.ordered

      hash
    end
  end

  def total_credits
    courses.map(&:credits).sum
  end

  def total_hours
    courses.map(&:hours).compact.sum
  end

  private

  def create_semester
    semesters.create(:kind => :no_matter)
  end

  def set_context_type(course)
    course.context_type = 'Semester'
  end

  def generate_number
    academic_records = self.class.where(:issue_date => (Date.today.beginning_of_year..Date.today.end_of_year), :faculty_id => self.faculty)

    if last_academic_record = academic_records.last
      number = last_academic_record.serial_number + 1
    else
      number = 1
    end
    formatted_number = sprintf("%05i",number)

    self.number = "#{faculty.eng_abbr.upcase}#{I18n.l(Date.today, :format => '%y')}-#{formatted_number}"
    self.serial_number = number
  end
end

# == Schema Information
#
# Table name: academic_records
#
#  id            :integer          not null, primary key
#  faculty_id    :integer
#  serial_number :integer
#  number        :string(255)
#  issued_on     :date
#  created_at    :datetime
#  updated_at    :datetime
#

app/controllers/academic_records_controller.rb
class AcademicRecordsController < CrudController
  def show
    show!{
      @course = @academic_record.courses.new
    }
  end

  def pdf
    @academic_record = AcademicRecord.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "#{@academic_record}-#{@academic_record.student}",
          :stylesheets => ["print_academic_records"]
      end
    end
  end

  def debug
    @academic_record = AcademicRecord.find(params[:id])
    respond_to do |format|
      format.html
    end
  end
end

app/views/academic_records/_form.html.erb
<%= form.fields_for :student do |student| %>
  <%= student.inputs do %>
    <%= student.input :surname, :input_html => {:tabindex => '1'}, :label => 'Имя' %>
    <%= student.input :firstname, :input_html => {:tabindex => '2'}, :label => 'Фамилия' %>
    <%= student.input :birthday, :input_html => {:tabindex => '8'} %>
  <% end %>
<% end %>

<%= form.inputs do %>
  <%= form.input :faculty, :wrapper_html => {:class => 'right wide'}, :input_html => {:tabindex => '9'} %>
  <%= form.input :admission_date %>
  <%= form.input :issue_date %>
<% end %>

<%= form.fields_for :semesters, @academic_record.semesters do |semester_fields| %>
  <%= semester_fields.inputs do %>
    <%= semester_fields.input :year, :input_html => {:tabindex => '1'} %>
    <%= semester_fields.input :kind, :input_html => {:tabindex => '1'} %>
    <li class='remove_link'>
      <%= semester_fields.link_to_remove 'Удалить' %>
    </li>
  <% end %>
<% end %>

<div class="add_link">
<%= form.link_to_add 'Добавить семестер', :semesters %>
</div>

app/views/academic_records/_item.html.erb
<li class="<%= item.class.name.downcase %> item">
  <h4>
    <%= link_to t(:edit), edit_resource_url(item), :class => "edit" %>

    <% if controller.respond_to?(:show) %>
      <%= link_to "#{item} - #{item.student_full_info}", resource_path(item) %>
    <% else %>
      <%= item.title %>
    <% end %>
  </h4>

  <% if item.respond_to? :translated? %>
    <% unless item.translated? %>
      <p><%= t('translate_missing') %></p>
    <% end %>
  <% end %>
</li>

app/views/academic_records/_search_form.html.erb
<%= semantic_search_form_for :academic_record, :url => academic_records_path, :html => {:method => :get, :class => 'search_form'} do |form| %>
  <%= form.inputs do %>
    <%= form.input :search_string %>
  <% end %>
  <%= form.buttons do %>
    <%= form.commit_button 'Найти', :button_html => {:class => 'button'} %>
  <% end %>
<% end %>

app/views/academic_records/debug.html.erb
<%= render :file => 'academic_records/pdf.pdf'%>

app/views/academic_records/pdf.html.erb
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.1//EN' 'http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
  <head>
    <meta http-equiv='Content-Type' content='text/html;charset=UTF-8' />
    <title><%= @academic_record %></title>
    <%= stylesheet_link_tag 'print_academic_records' %>
  </head>
  <body>
    <div class='wrapper'>

      <div class='header'>
          <div class='right_info'>
            <ul>
              <li><%= @academic_record.faculty.eng_title %></li>
              <li><span class='strong'><%= @academic_record.student %></span></li>
              <li>Registration №: <%= @academic_record.number %></li>
              <li>Date of Birth: <%= @academic_record.student.birthday.strftime('%B %d, %Y') %></li>
              <li>Date of Admission: <%= @academic_record.admission_date.strftime('%B %d, %Y') %></li>
              <li>Date of Issue: <%= @academic_record.issue_date.strftime('%B %d, %Y') %></li>
            </ul>
          </div>
      </div>

      <div class='content'>
        <table>
          <thead>
            <tr>
              <th></th>
              <th class='course_title'>Course Title</th>
              <th class='credits'>Credits</th>
              <th class='hours'>Hours</th>
              <th class='grades'>Grades</th>
            </tr>
          </thead>
          <tbody>
            <% @academic_record.courses_grouped_by_semester.each do |semester, courses| %>
              <% courses.each_with_index do |course, index| %>
              <tr>
                <% if index.zero? %>
                  <td rowspan="<%= courses.count %>" class='semester'><%= semester %></td>
                <% end %>
                <td class='course_title'><%= course.eng_title %></td>
                <td class='credits'><%= course.credits %></td>
                <td class='hours'><%= course.hours.to_i > 0 ? course.hours : '-' %></td>
                <td class='grades'><%= course.human_grade_eng %></td>
              </tr>
              <% end %>
            <% end %>
              <tr>
                <td style="border: none"></td>
                <td class='total_title'>Total</td>
                <td class='total_credits'><%= @academic_record.total_credits %></td>
                <td class='total_hours'><%= @academic_record.total_hours %></td>
                <td style="border: none"></td>
              </tr>
          </tbody>
        </table>
      </div>

      <div class='sign'>
        <div class='left_sign'>
          <div class='fio strong'><%= t 'rector_name' %></div>
          <%= t 'rector_post' %>
        </div>
        <div class='right_sign'>
          <div class='fio strong'><%= @academic_record.faculty.chief_name %></div>
          <%= @academic_record.faculty.chief_post %>
          <%= "#{@academic_record.faculty.eng_title}" %>
        </div>
      </div>

    </div>
  </body>
  </html>

app/views/academic_records/pdf.pdf.erb
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.1//EN' 'http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
  <head>
    <meta http-equiv='Content-Type' content='text/html;charset=UTF-8' />
    <title><%= @academic_record %></title>
    <%= stylesheet_link_tag 'print_academic_records' %>
  </head>
  <body>
    <div class='wrapper'>

      <div class='header'>
          <div class='right_info'>
            <ul>
              <li><%= @academic_record.faculty.eng_title %></li>
              <li><span class='strong'><%= @academic_record.student %></span></li>
              <li>Registration №: <%= @academic_record.number %></li>
              <li>Date of Birth: <%= @academic_record.student.birthday.strftime('%B %d, %Y') %></li>
              <li>Date of Admission: <%= @academic_record.admission_date.strftime('%B %d, %Y') %></li>
              <li>Date of Issue: <%= @academic_record.issue_date.strftime('%B %d, %Y') %></li>
            </ul>
          </div>
      </div>

      <div class='content'>
        <table>
          <thead>
            <tr>
              <th></th>
              <th class='course_title'>Course Title</th>
              <th class='credits'>Credits</th>
              <th class='hours'>Hours</th>
              <th class='grades'>Grades</th>
            </tr>
          </thead>
          <tbody>
            <% @academic_record.courses_grouped_by_semester.each do |semester, courses| %>
              <% courses.each_with_index do |course, index| %>
              <tr>
                <% if index.zero? %>
                  <td rowspan="<%= courses.count %>" class='semester'><%= semester %></td>
                <% end %>
                <td class='course_title'><%= course.eng_title %></td>
                <td class='credits'><%= course.credits %></td>
                <td class='hours'><%= course.hours.to_i > 0 ? course.hours : '-' %></td>
                <td class='grades'><%= course.human_grade_eng %></td>
              </tr>
              <% end %>
            <% end %>
              <tr>
                <td style="border: none"></td>
                <td class='total_title'>Total</td>
                <td class='total_credits'><%= @academic_record.total_credits %></td>
                <td class='total_hours'><%= @academic_record.total_hours %></td>
                <td style="border: none"></td>
              </tr>
          </tbody>
        </table>
      </div>

      <div class='sign'>
        <div class='left_sign'>
          <div class='fio strong'><%= t 'rector_name' %></div>
          <%= t 'rector_post' %>
        </div>
        <div class='right_sign'>
          <div class='fio strong'><%= @academic_record.faculty.chief_name %></div>
          <%= @academic_record.faculty.chief_post %>
          <%= "#{@academic_record.faculty.eng_title}" %>
        </div>
      </div>

    </div>
  </body>
  </html>

app/views/academic_records/show.html.erb
<% title resource %>

<%= link_to t(:edit), edit_academic_record_path, :class => 'button floatr' %>
<%= link_to 'Печать шаблона', pdf_academic_record_path(resource), :class => 'button floatr print' %>

<%= show_for resource do |item| %>
  <%= item.association :student, :using => :full_info %>
  <%= item.attributes :number, :admission_date, :issue_date %>
<% end %>

<div class='details_wrapper'>
  <ul class='details'>
    <li id='courses'>
      <div class="headline">
        <span class='title'>Название</span>
        <span class='eng_title'>Название на англ. языке</span>
        <span class='credits'>Баллы</span>
        <span class='hours'>Часы</span>
        <span class='human_grade'>Оценка</span>
      </div>
      <ol class='courses_list list' id='courses_list' data-sort-url="<%= sort_academic_record_courses_path(resource) %>">
        <% if @academic_record.courses.any? %>
          <% @academic_record.courses.ordered.each do |course| %>
            <li class="item" id="programm_item_<%= course.id %>">
              <%= render :partial => "courses/course", :locals => {:course => course} %>
            </li>
          <% end %>
        <% else %>
          <li class='empty'>нет дисциплин</li>
        <% end %>
      </ol>
      <div class='form_new'>
        <%= render :file => "courses/new.html.erb" %>
      </div>
    </li>
  </ul>
</div>