config/routes.rb
TusurDiplomer::Application.routes.draw do
  devise_for :users

  match 'diplomas/:id/pdf' => 'diplomas#pdf', :defaults => {:format => :pdf}, :as => 'pdf_diploma'
  match 'academic_records/:id/pdf' => 'academic_records#pdf', :defaults => {:format => :pdf}, :as => 'pdf_academic_record'

  match 'academic_records/:id/debug' => 'academic_records#debug'

  resources :diplomas do
    resources :student
    resources :courses
    resources :papers
    resources :practices
    resources  :final_state_examinations

    resource  :final_qualification_project

    resources :programm_items, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :academic_records do
    resources :courses

    resources :courses, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :chairs
  resources :disciplines,  :except => :show
  resources :faculties,    :except => :show

  resources :specialities do
    resources :courses
    resources :papers
    resources :practices
    resources  :final_state_examinations
    resources :programm_items, :only => [] do
      post :sort, :on => :collection
    end
  end

  resources :suggestions,  :only => :index
  resources :users

  resources :people do
    resources :roles, :except => [:index,:show]
  end

  root :to => "application#index"
end

app/controllers/crud_controller.rb
# encoding: utf-8

class CrudController < ApplicationController
  has_searcher

  inherit_resources

  render_inheritable

  helper_method :render_new_button?

  protected
    def collection
        get_collection_ivar || set_collection_ivar(search_and_paginate_collection)
    end

    def search_and_paginate_collection
        if params[:utf8]
          searcher.pagination = paginate_options
          searcher.results
        else
          end_of_association_chain.paginate(paginate_options)
        end
    end

    def paginate_options(options={})
      {
        :page       => params[:page],
        :per_page   => per_page
      }.merge(options)
    end

    def per_page
      15
    end

    def render_new_button?
      respond_to? :new
    end
end

app/views/crud/_form.html.erb
<%= form.inputs %>

app/views/crud/_item.html.erb
<li class="<%= item.class.name.downcase %> item">
  <h4>
    <%= link_to t(:edit), edit_resource_url(item), :class => "edit" %>

    <% if controller.respond_to?(:show) %>
      <%= link_to item, resource_path(item) %>
    <% else %>
      <%= item.title %>
    <% end %>
  </h4>

  <% if item.respond_to? :translated? %>
    <% unless item.translated? %>
      <p><%= t('translate_missing') %></p>
    <% end %>
  <% end %>
</li>

app/views/crud/_view.html.erb
<%= show_for resource do |obj|%>
  <% resource.attributes.keys.each do |field|%>
    <% next if ['id', 'created_at', 'updated_at', 'old_id'].include?(field)%>
    <%= field.scan(/_id$/) ? obj.association(field.sub(/_id$/, "").to_sym) : obj.attribute(field.to_sym)%>
  <% end%>
<% end%>

app/views/crud/delete.html.erb
<h2><%= resource %></h2>

<% if resource.protected? %>
  <p>Нельзя удалить этот объект, пока существуют связанные объекты.</p>
<% else %>
  <p>Вы уверены что хотите удалить?</p>
<% end %>

<%= show_for resource do |s| %>
  <% unless resource.protected_children.empty? %>
      С этим объектом связаны:
      <% resource.protected_children.each do |association| %>
        <%= s.association association.to_sym %>
      <% end %>
  <% end %>
<% end %>

<%= semantic_form_for resource, :url => resource_path, :html => {:method => :delete} do |form| %>
  <%= form.error_messages %>
  <%= form.buttons do %>
    <%= form.commit_button t(:destroy), :button_html => {:class => 'button red'} %>
    <li>
      <%= link_to content_tag(:span, t(:cancel), :class => 'inner'),
                  smart_resource_url,
                  :class => 'button cancel' %>
    </li>
  <% end %>
<% end %>

app/views/crud/edit.html.erb
<% title "#{resource.class.model_name.human}. #{t('Changing information')}" %>

<%= semantic_nested_form_for resource, :url => resource_url do |form| %>
  <%= form.error_messages %>
  <%= render :partial => "form", :object => form %>
  <%= form.buttons do %>
    <%= form.commit_button :button_html => { :class => "button" } %>
    <li><%= link_to t(:cancel), smart_resource_url, :class => "button light" %></li>
    <li class="floatr"><%= link_to t(:destroy), delete_resource_url, :class => "button red light" %></li>
  <% end %>
<% end %>

app/views/crud/index.html.erb
<% title resource_class.model_name.human %>

<div class="actions">
  <%= link_to t(:new), new_resource_url, :class => "button floatr" %>
  <%= render :partial => "search_form" %>
</div>

<% if collection.any? %>
  <ul class="<%= resource_class.name.downcase.pluralize %>_list collection ">
    <% collection.each do |obj| %>
      <%= render :partial => "item", :locals => { :item => obj } %>
    <% end %>
  </ul>
  <%= will_paginate collection %>
<% end %>

app/views/crud/new.html.erb
<% title "#{resource.class.model_name.human}. #{t('Adding information')}" %>

<%= semantic_nested_form_for resource, :url => collection_url do |form| %>
  <%= form.error_messages %>
  <%= render :partial => "form", :object => form %>
  <%= form.buttons do %>
    <%= form.commit_button :button_html => { :class => "button" } %>
    <li><%= link_to t(:cancel), smart_resource_url, :class => "button light" %></li>
  <% end %>
<% end %>

app/views/crud/show.html.erb
<div class="formtastic">
  <fieldset>
    <legend><%= resource %></legend>
    <%= render :partial => "view" %>
  </fieldset>
  <fieldset class="buttons">
    <ol>
      <li><%= link_to t(:edit), edit_resource_url, :class => "button" %></li>
    </ol>
  </fieldset>
</div>